name: Build UnlockBuzz from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o UnlockBuzz.zip -d .
          ls -la
          test -d UnlockBuzz || { echo "UnlockBuzz/ 폴더가 ZIP 안에 없어요"; exit 1; }

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Build Debug APK
        working-directory: UnlockBuzz
        run: gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: UnlockBuzz/app/build/outputs/apk/debug/*.apk
